# Generated by Django 6.0.4 on 2026-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_fieldupdate_assigned_agent_alter_fieldupdate_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='residence',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
