# Generated by Django 6.0.5 on 2026-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_profile_phone_profile_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldupdate',
            name='disease_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldupdate',
            name='irrigation_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldupdate',
            name='pest_detected',
            field=models.BooleanField(default=False),
        ),
    ]
