# Generated by Django 6.0.4 on 2026-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('field_agent', 'Field Agent')], default='field_agent', max_length=20),
        ),
    ]
